esphome:
  name: esp1
  friendly_name: ESP1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WjVCE1GdbfTRoIrUcuCZZ9/4oxQDEkLTnJj/rVPtbAc="

ota:
  - platform: esphome
    password: "909434005fb560279f3b1de97a1be3fc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp1 Fallback Hotspot"
    password: "PU5MuBOydZHV"

captive_portal:
    