esphome:
  name: "tv-mount"
  friendly_name: tvmount
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: "Aggarwin"
  password: "4432041701"

captive_portal:

switch:
  - platform: gpio
    pin: 13
    id: down_switch
    internal: true
    restore_mode: always_off
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: down_switch

  - platform: gpio
    pin: 14
    id: up_switch
    internal: true
    restore_mode: always_off
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: up_switch

button:
  - platform: template
    name: "Lower Screen"
    icon: "mdi:chevron-down"
    on_press:
      then:
        - switch.turn_on: down_switch

  - platform: template
    name: "Return Screen"
    icon: "mdi:chevron-up"
    on_press:
      then:
        - switch.turn_on: up_switch


          

