esphome:
  name: tvmount
  friendly_name: TVMount

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lTfgzofZxEyC+JKWmFi0Gh+t6u06pWKzQv3T2SZ/2cA="

ota:
  - platform: esphome
    password: "1a971de1930728e0ee01f08cc2a3599f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tvmount Fallback Hotspot"
    password: "dfsPkKy8RacT"

captive_portal:
    